name: Cross

on:
  push:
    branches:
      - main
    tags:
      - "*"
      - "**"

  pull_request:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  envfile: ${{secrets.ENV}}
  MODE: test
  NODE_ENV: testing


jobs:
  build-and-test:
#    concurrency: db-test # DB not required for unit tests

    timeout-minutes: 10
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 2 #Now that concurrency is enabled
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest] #,windows-latest]
        node_version: [18, 19,20]
        architecture: [ x64] # , arm] #, arm64 ]
    #        include:
    #          - os: windows-2016
    #            node_version: 16
    #            architecture: x86

    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.6

      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          check-latest: true

      - name: Install dependencies
        run: pnpm install

      - name: Prisma generate
        run: npx prisma generate

      - name: Build
        run: pnpm build

      - name: Write environment #TODO: add coachroach ssl certificate
        run: |
          echo $envfile > .env.tmp
          sed 's/ /\n/g' .env.tmp > .env
          source .env

      - name: Run tests for ${{runner.os}}
        run: pnpm test

#      - name: E2E
#        run: pnpm test:e2e
