name: E2E

on:
  push:
    branches:
      - main
#      - "*"
#      - "**"
    tags:
      - "*"
      - "**"

  pull_request:
    branches:
      - main
  merge_group:
    types: [ checks_requested ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  envfile: ${{secrets.ENV}}
  MODE: test
  NODE_ENV: test

jobs:
  build-and-test:
    concurrency: db-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.6

      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: 19
          check-latest: true

      - name: Install dependencies
        run: pnpm install

      - name: Prisma generate
        run: npx prisma generate

      - name: Build
        run: pnpm build

      - name: Write environment
        run: |
          echo $envfile > .env
          sed -i 's/ /\n/g' .env
          source .env

      - name: Prisma Migration
        continue-on-error: true
        run: |
          echo "Migrating DB"
          #npx prisma migrate reset --force
          npx prisma migrate deploy

      - name: Reset the DB
        if: ${{ failure() }}
        run: |
          prisma migrate dev

      - name: Run tests
        run: pnpm run test

      - name: E2E
        run: pnpm test:e2e
